# Generated by Django 4.0.3 on 2022-03-28 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userportfolioinfo',
            old_name='profile_pics',
            new_name='profile_pic',
        ),
    ]
